webtalk_init -webtalk_dir J:/ECEN 323 Labs/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/vga_timing_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jan 13 14:22:07 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2644227" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174672765_1777505556_210698736_928" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7c136ded-f9df-4047-b432-8fec692117cd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "617541cab61b42e3bfe1a6fbb8a27250" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "14446455 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14056_KB" -context "xsim\\usage"
webtalk_transmit -clientid 247409362 -regid "174672765_1777505556_210698736_928" -xml J:/ECEN 323 Labs/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/vga_timing_behav/webtalk/usage_statistics_ext_xsim.xml -html J:/ECEN 323 Labs/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/vga_timing_behav/webtalk/usage_statistics_ext_xsim.html -wdm J:/ECEN 323 Labs/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/vga_timing_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
