# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {J:/ECEN 220 Labs/Lab8_SevenSegmentController/Lab8_SevenSegmentController.cache/wt} [current_project]
set_property parent.project_path {J:/ECEN 220 Labs/Lab8_SevenSegmentController/Lab8_SevenSegmentController.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {j:/ECEN 220 Labs/Lab8_SevenSegmentController/Lab8_SevenSegmentController.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {J:/ECEN 220 Labs/Lab8_SevenSegmentController/Lab8_SevenSegmentController.srcs/sources_1/new/SevenSegmentControl.sv}
  {J:/ECEN 220 Labs/Lab8_SevenSegmentController/Lab8_SevenSegmentController.srcs/sources_1/new/SevenSegmentControlTop.sv}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{J:/ECEN 220 Labs/Lab8_SevenSegmentController/Lab8_SevenSegmentController.srcs/constrs_1/new/MasterConnect.xdc}}
set_property used_in_implementation false [get_files {{J:/ECEN 220 Labs/Lab8_SevenSegmentController/Lab8_SevenSegmentController.srcs/constrs_1/new/MasterConnect.xdc}}]


synth_design -top SevenSegmentControlTop -part xc7a100tcsg324-1


write_checkpoint -force -noxdef SevenSegmentControlTop.dcp

catch { report_utilization -file SevenSegmentControlTop_utilization_synth.rpt -pb SevenSegmentControlTop_utilization_synth.pb }
