@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Feb 21 11:04:04 -0700 2020
REM SW Build 2644227 on Wed Sep  4 09:45:24 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim single_cycle_mem_tb_behav -key {Behavioral:sim_2:Functional:single_cycle_mem_tb} -tclbatch single_cycle_mem_tb.tcl -log simulate.log"
call xsim  single_cycle_mem_tb_behav -key {Behavioral:sim_2:Functional:single_cycle_mem_tb} -tclbatch single_cycle_mem_tb.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
